# Generated by Django 5.2.1 on 2025-06-06 17:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(blank=True, null=True)),
                ('input_audio', models.FileField(blank=True, null=True, upload_to='conversions/input/%Y/%m/%d/')),
                ('output_audio', models.FileField(upload_to='conversions/output/%Y/%m/%d/')),
                ('processing_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('progress', models.FloatField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='voicemodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='voicesample',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='voicemodel',
            name='batch_size',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='voicemodel',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicemodel',
            name='config_path',
            field=models.CharField(default='models/default_config.json', max_length=255),
        ),
        migrations.AddField(
            model_name='voicemodel',
            name='epochs',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='voicemodel',
            name='learning_rate',
            field=models.FloatField(default=0.0001),
        ),
        migrations.AddField(
            model_name='voicemodel',
            name='loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicemodel',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='voicemodel',
            name='progress',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='voicemodel',
            name='sample_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicemodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='voicemodel',
            name='training_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='voicesample',
            name='audio_quality',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='voicesample',
            name='channels',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voicesample',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicesample',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicesample',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicesample',
            name='sample_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicesample',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('valid', 'Valid'), ('invalid', 'Invalid')], default='uploaded', max_length=10),
        ),
        migrations.AddField(
            model_name='voicesample',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voicemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voicesample',
            name='audio_file',
            field=models.FileField(upload_to='voice_samples/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='voicesample',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='voicesample',
            index=models.Index(fields=['user', 'status'], name='voiceapi_vo_user_id_7080ea_idx'),
        ),
        migrations.AddIndex(
            model_name='voicesample',
            index=models.Index(fields=['created_at'], name='voiceapi_vo_created_e25c79_idx'),
        ),
        migrations.AddConstraint(
            model_name='voicemodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_model_per_user'),
        ),
        migrations.AddField(
            model_name='audioconversion',
            name='model_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voiceapi.voicemodel'),
        ),
        migrations.AddField(
            model_name='audioconversion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_conversions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingtask',
            name='voice_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voiceapi.voicemodel'),
        ),
        migrations.AddIndex(
            model_name='trainingtask',
            index=models.Index(fields=['task_id'], name='voiceapi_tr_task_id_1b1825_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingtask',
            index=models.Index(fields=['user', 'status'], name='voiceapi_tr_user_id_a59b2c_idx'),
        ),
    ]
